### PR TITLE
update version to 3.0.0

### PR DESCRIPTION
**Pull request by zhouyuguangsc**
support Nebula Graph 3.0.0

### CODE REVIEW

**Comment by zhouyuguangsc** [comment]
How does the unit test pass

**Comment by heyanlong** [comment]
Check the error https://github.com/nebula-contrib/nebula-net/runs/5403332080?check_suite_focus=true log and fix it

**Comment by zhouyuguangsc** [comment]
No, the unit test failed to connect to the database

**Comment by heyanlong** [comment]
Need to update https://github.com/nebula-contrib/nebula-net/blob/master/docker-compose.yaml to 3.x

**Comment by heyanlong** [comment]
I don't think it's as simple as changing the version number.

**Comment by zhouyuguangsc** [comment]
A command needs to be executed：ADD HOSTS <ip>:<port> [,<ip>:<port> ...];

**Comment by zhouyuguangsc** [comment]
I gave up and didn't know why I couldn't succeed

**Comment by wey-gu** [comment]
Sorry for driving you crazy 😭, I will try helping you out there.

**Comment by heyanlong** [comment]
@shyboylpf it's time to show up

**Comment by wey-gu** [comment]
> I gave up and didn't know why I couldn't succeed

The reason why 127.0.0.1:9779 won't help are:
- Add host is an extra phase added in nebula service discovery
  - previously all service will push their own info to meta, and meta will treat them as a service to be ready to put data/traffic to
  - since 3.0, the services self-reported to metaD are considered as registered, then, it's required to explicit activate them to ensure they could be used
 - From any nebula services running in docker, 127.0.0.1 won't reach out of its own container as it's a loopback address, instead, domain names like storaged0, metad0 were used(as the internal IP is actually dynamic)

**Comment by zhouyuguangsc** [comment]
> > I gave up and didn't know why I couldn't succeed
> 
> The reason why 127.0.0.1:9779 won't help are:
> 
> * Add host is an extra phase added in nebula service discovery
>   
>   * previously all service will push their own info to meta, and meta will treat them as a service to be ready to put data/traffic to
>   * since 3.0, the services self-reported to metaD are considered as registered, then, it's required to explicit activate them to ensure they could be used
> * From any nebula services running in docker, 127.0.0.1 won't reach out of its own container as it's a loopback address, instead, domain names like storaged0, metad0 were used(as the internal IP is actually dynamic)

thanks!
I tried to write the service name directly, But the prompt syntax is wrong. Originally, it was not added “”

**Comment by heyanlong** [comment]
LGTM

**Comment by shyboylpf** [comment]
Looks good, thank you all!

**Pull request merged**
